Host: "127.0.0.1:8086"
QQBotUid: "123456789"
devicename: "æä¸‰å–µğŸ±"
json: "1"
BotToken: "123456789abcdefg"
receive_forbidden:
  - 856337734

send_forbidden:
  - 123456789

super_users:
  - 123456789

## æ’ä»¶é…ç½®

checkin:
  - 123456789: "ç­¾åˆ°"
